### PR TITLE
updated code with new sdk

### PR DESCRIPTION
**Pull request by nishchhaldagar**

### CODE REVIEW

**Comment by augustogoncalves** [comment]
@petrbroz this is a first review, to confirm if the code looks good. We did a similar PR for view models tutorial code.

**Comment by petrbroz** [comment]
Thanks guys. @augustogoncalves I have reviewed the code, and it looks good to me, but I'm a bit hesitant to merge this PR at this point because:

- we have another online bootcamp coming up at the end of January 2024
- we would need to test the new SDKs properly before that
- we would need to update the docusaurus tutorials with the new code
- not sure if it's a good idea to use _beta_ SDKs in the official tutorials

I would prefer if we kept the new SDKs in a separate branch so that we and the customers can easily test it out. And when the SDKs are out of beta, we could incorporate them into the official tutorials.

**Comment by augustogoncalves** [comment]
@petrbroz correct, for now is about reviewing & feedback

**Comment by petrbroz** [comment]
Closing. The code has already been updated to the latest beta version of the SDKs.

**Pull request closed without merging**
